apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: c54ydf85i-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:a7869f1780fa668ff6ba1ad0b3ad2fd4c4dd8be1@sha256:8211e252d680574928e5efacca72149872f252799ca6ee5d03d0a2781ed2972d
          name: container-image
